CREATE TABLE `accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`parent_id` int,
	`level` int DEFAULT 1,
	`type` enum('asset','liability','equity','revenue','expense') NOT NULL,
	`nature` enum('debit','credit') NOT NULL,
	`is_parent` boolean DEFAULT false,
	`is_active` boolean DEFAULT true,
	`is_cash_account` boolean DEFAULT false,
	`is_bank_account` boolean DEFAULT false,
	`currency` varchar(10) DEFAULT 'SAR',
	`opening_balance` decimal(18,2) DEFAULT '0',
	`current_balance` decimal(18,2) DEFAULT '0',
	`description` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`station_id` int,
	`equipment_id` int,
	`sensor_id` int,
	`alert_type` enum('info','warning','critical','emergency') NOT NULL,
	`category` varchar(50),
	`title` varchar(255) NOT NULL,
	`message` text,
	`value` decimal(15,4),
	`threshold` decimal(15,4),
	`status` enum('active','acknowledged','resolved','escalated') DEFAULT 'active',
	`triggered_at` timestamp NOT NULL DEFAULT (now()),
	`acknowledged_by` int,
	`acknowledged_at` timestamp,
	`resolved_by` int,
	`resolved_at` timestamp,
	`resolution` text,
	`work_order_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `asset_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`parent_id` int,
	`depreciation_method` enum('straight_line','declining_balance','units_of_production') DEFAULT 'straight_line',
	`useful_life` int,
	`salvage_percentage` decimal(5,2) DEFAULT '0',
	`asset_account_id` int,
	`depreciation_account_id` int,
	`accumulated_dep_account_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `asset_categories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `asset_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`asset_id` int NOT NULL,
	`movement_type` enum('purchase','transfer','maintenance','upgrade','revaluation','impairment','disposal','depreciation') NOT NULL,
	`movement_date` date NOT NULL,
	`from_branch_id` int,
	`to_branch_id` int,
	`from_station_id` int,
	`to_station_id` int,
	`amount` decimal(18,2),
	`description` text,
	`reference_type` varchar(50),
	`reference_id` int,
	`journal_entry_id` int,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `asset_movements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`category_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`serial_number` varchar(100),
	`model` varchar(100),
	`manufacturer` varchar(100),
	`purchase_date` date,
	`commission_date` date,
	`purchase_cost` decimal(18,2) DEFAULT '0',
	`current_value` decimal(18,2) DEFAULT '0',
	`accumulated_depreciation` decimal(18,2) DEFAULT '0',
	`salvage_value` decimal(18,2) DEFAULT '0',
	`useful_life` int,
	`depreciation_method` enum('straight_line','declining_balance','units_of_production'),
	`status` enum('active','maintenance','disposed','transferred','idle') DEFAULT 'active',
	`location` varchar(255),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`warranty_expiry` date,
	`supplier_id` int,
	`purchase_order_id` int,
	`parent_asset_id` int,
	`qr_code` varchar(255),
	`barcode` varchar(100),
	`image` text,
	`specifications` json,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int,
	`user_id` int,
	`action` varchar(50) NOT NULL,
	`module` varchar(50) NOT NULL,
	`entity_type` varchar(50),
	`entity_id` int,
	`old_values` json,
	`new_values` json,
	`ip_address` varchar(50),
	`user_agent` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `branches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('main','regional','local') NOT NULL DEFAULT 'local',
	`parent_id` int,
	`address` text,
	`city` varchar(100),
	`region` varchar(100),
	`country` varchar(100) DEFAULT 'Saudi Arabia',
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`phone` varchar(50),
	`email` varchar(255),
	`manager_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `branches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `businesses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('holding','subsidiary','branch') NOT NULL DEFAULT 'subsidiary',
	`parent_id` int,
	`logo` text,
	`address` text,
	`phone` varchar(50),
	`email` varchar(255),
	`website` varchar(255),
	`tax_number` varchar(50),
	`commercial_register` varchar(50),
	`currency` varchar(10) DEFAULT 'SAR',
	`fiscal_year_start` int DEFAULT 1,
	`timezone` varchar(50) DEFAULT 'Asia/Riyadh',
	`is_active` boolean DEFAULT true,
	`settings` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `businesses_id` PRIMARY KEY(`id`),
	CONSTRAINT `businesses_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `cost_centers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`parent_id` int,
	`level` int DEFAULT 1,
	`type` enum('station','department','project','activity'),
	`station_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cost_centers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`account_number` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('residential','commercial','industrial','government','agricultural') DEFAULT 'residential',
	`category` varchar(50),
	`id_type` enum('national_id','iqama','passport','cr'),
	`id_number` varchar(50),
	`phone` varchar(50),
	`mobile` varchar(50),
	`email` varchar(255),
	`address` text,
	`city` varchar(100),
	`district` varchar(100),
	`postal_code` varchar(20),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`tariff_id` int,
	`connection_date` date,
	`status` enum('active','suspended','disconnected','closed') DEFAULT 'active',
	`current_balance` decimal(18,2) DEFAULT '0',
	`deposit_amount` decimal(18,2) DEFAULT '0',
	`credit_limit` decimal(18,2),
	`account_id` int,
	`is_active` boolean DEFAULT true,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`station_id` int NOT NULL,
	`asset_id` int,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('transformer','generator','switchgear','breaker','relay','meter','sensor','inverter','battery','panel','cable','motor') NOT NULL,
	`status` enum('online','offline','maintenance','fault','unknown') DEFAULT 'unknown',
	`manufacturer` varchar(100),
	`model` varchar(100),
	`serial_number` varchar(100),
	`rated_capacity` decimal(15,2),
	`capacity_unit` varchar(20),
	`voltage_rating` varchar(50),
	`current_rating` varchar(50),
	`installation_date` date,
	`last_maintenance_date` date,
	`next_maintenance_date` date,
	`location` varchar(255),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`is_controllable` boolean DEFAULT false,
	`is_monitored` boolean DEFAULT true,
	`communication_protocol` varchar(50),
	`ip_address` varchar(50),
	`metadata` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `equipment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fiscal_periods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`year` int NOT NULL,
	`period` int NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`start_date` date NOT NULL,
	`end_date` date NOT NULL,
	`status` enum('open','closed','locked') DEFAULT 'open',
	`closed_by` int,
	`closed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fiscal_periods_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`customer_id` int NOT NULL,
	`meter_id` int,
	`invoice_number` varchar(50) NOT NULL,
	`invoice_date` date NOT NULL,
	`due_date` date NOT NULL,
	`period_start` date,
	`period_end` date,
	`reading_id` int,
	`consumption` decimal(15,3),
	`consumption_amount` decimal(18,2) DEFAULT '0',
	`fixed_charges` decimal(18,2) DEFAULT '0',
	`tax_amount` decimal(18,2) DEFAULT '0',
	`other_charges` decimal(18,2) DEFAULT '0',
	`discount_amount` decimal(18,2) DEFAULT '0',
	`previous_balance` decimal(18,2) DEFAULT '0',
	`total_amount` decimal(18,2) DEFAULT '0',
	`paid_amount` decimal(18,2) DEFAULT '0',
	`balance_due` decimal(18,2) DEFAULT '0',
	`status` enum('draft','issued','sent','partial','paid','overdue','cancelled') DEFAULT 'draft',
	`journal_entry_id` int,
	`notes` text,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `item_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`parent_id` int,
	`inventory_account_id` int,
	`cogs_account_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `item_categories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`category_id` int,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`type` enum('spare_part','consumable','raw_material','finished_good') DEFAULT 'spare_part',
	`unit` varchar(20) NOT NULL,
	`barcode` varchar(100),
	`min_stock` decimal(15,3) DEFAULT '0',
	`max_stock` decimal(15,3),
	`reorder_point` decimal(15,3),
	`reorder_qty` decimal(15,3),
	`standard_cost` decimal(18,4) DEFAULT '0',
	`last_purchase_price` decimal(18,4),
	`average_cost` decimal(18,4),
	`is_active` boolean DEFAULT true,
	`image` text,
	`specifications` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `journal_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`entry_number` varchar(50) NOT NULL,
	`entry_date` date NOT NULL,
	`period_id` int NOT NULL,
	`type` enum('manual','auto','opening','closing','adjustment','invoice','payment','receipt','transfer','depreciation') DEFAULT 'manual',
	`source_module` varchar(50),
	`source_id` int,
	`description` text,
	`total_debit` decimal(18,2) DEFAULT '0',
	`total_credit` decimal(18,2) DEFAULT '0',
	`status` enum('draft','posted','reversed') DEFAULT 'draft',
	`posted_by` int,
	`posted_at` timestamp,
	`reversed_by` int,
	`reversed_at` timestamp,
	`reversal_entry_id` int,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `journal_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `journal_entry_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entry_id` int NOT NULL,
	`line_number` int NOT NULL,
	`account_id` int NOT NULL,
	`cost_center_id` int,
	`description` text,
	`debit` decimal(18,2) DEFAULT '0',
	`credit` decimal(18,2) DEFAULT '0',
	`currency` varchar(10) DEFAULT 'SAR',
	`exchange_rate` decimal(10,6) DEFAULT '1',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `journal_entry_lines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`asset_category_id` int,
	`frequency` enum('daily','weekly','monthly','quarterly','semi_annual','annual') NOT NULL,
	`interval_days` int,
	`based_on` enum('calendar','meter','condition') DEFAULT 'calendar',
	`meter_type` varchar(50),
	`meter_interval` decimal(15,2),
	`estimated_hours` decimal(8,2),
	`estimated_cost` decimal(18,2),
	`is_active` boolean DEFAULT true,
	`tasks` json,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meter_readings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meter_id` int NOT NULL,
	`reading_date` date NOT NULL,
	`reading_value` decimal(15,3) NOT NULL,
	`previous_reading` decimal(15,3),
	`consumption` decimal(15,3),
	`reading_type` enum('actual','estimated','adjusted') DEFAULT 'actual',
	`read_by` int,
	`image` text,
	`notes` text,
	`status` enum('pending','verified','billed','disputed') DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meter_readings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`meter_number` varchar(50) NOT NULL,
	`type` enum('single_phase','three_phase','smart','prepaid') DEFAULT 'single_phase',
	`status` enum('active','inactive','faulty','replaced') DEFAULT 'active',
	`installation_date` date,
	`last_reading_date` date,
	`last_reading` decimal(15,3),
	`multiplier` decimal(10,4) DEFAULT '1',
	`max_load` decimal(10,2),
	`location` varchar(255),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`manufacturer` varchar(100),
	`model` varchar(100),
	`serial_number` varchar(100),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meters_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`customer_id` int NOT NULL,
	`payment_number` varchar(50) NOT NULL,
	`payment_date` date NOT NULL,
	`amount` decimal(18,2) NOT NULL,
	`payment_method` enum('cash','card','bank_transfer','check','online','sadad') DEFAULT 'cash',
	`reference_number` varchar(100),
	`bank_account_id` int,
	`status` enum('pending','completed','failed','refunded') DEFAULT 'completed',
	`notes` text,
	`journal_entry_id` int,
	`received_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `permissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`module` varchar(50) NOT NULL,
	`code` varchar(100) NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`description` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `permissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `permissions_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `project_phases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`project_id` int NOT NULL,
	`phase_number` int NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`start_date` date,
	`end_date` date,
	`actual_start_date` date,
	`actual_end_date` date,
	`budget` decimal(18,2),
	`actual_cost` decimal(18,2) DEFAULT '0',
	`progress` decimal(5,2) DEFAULT '0',
	`status` enum('pending','in_progress','completed','cancelled') DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_phases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`project_id` int NOT NULL,
	`phase_id` int,
	`parent_task_id` int,
	`task_number` varchar(50),
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`type` enum('task','milestone') DEFAULT 'task',
	`status` enum('pending','in_progress','completed','cancelled') DEFAULT 'pending',
	`priority` enum('low','medium','high') DEFAULT 'medium',
	`assigned_to` int,
	`start_date` date,
	`end_date` date,
	`actual_start_date` date,
	`actual_end_date` date,
	`estimated_hours` decimal(8,2),
	`actual_hours` decimal(8,2),
	`progress` decimal(5,2) DEFAULT '0',
	`dependencies` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`description` text,
	`type` enum('construction','expansion','maintenance','upgrade','installation','decommission','study') NOT NULL,
	`status` enum('planning','approved','in_progress','on_hold','completed','cancelled','closed') DEFAULT 'planning',
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`manager_id` int,
	`start_date` date,
	`planned_end_date` date,
	`actual_end_date` date,
	`budget` decimal(18,2),
	`actual_cost` decimal(18,2) DEFAULT '0',
	`progress` decimal(5,2) DEFAULT '0',
	`cost_center_id` int,
	`approved_by` int,
	`approved_at` timestamp,
	`closed_by` int,
	`closed_at` timestamp,
	`notes` text,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `purchase_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`order_number` varchar(50) NOT NULL,
	`order_date` date NOT NULL,
	`supplier_id` int NOT NULL,
	`status` enum('draft','pending','approved','sent','partial_received','received','cancelled','closed') DEFAULT 'draft',
	`delivery_date` date,
	`warehouse_id` int,
	`payment_terms` int,
	`currency` varchar(10) DEFAULT 'SAR',
	`exchange_rate` decimal(10,6) DEFAULT '1',
	`subtotal` decimal(18,2) DEFAULT '0',
	`tax_amount` decimal(18,2) DEFAULT '0',
	`discount_amount` decimal(18,2) DEFAULT '0',
	`total_amount` decimal(18,2) DEFAULT '0',
	`paid_amount` decimal(18,2) DEFAULT '0',
	`notes` text,
	`terms` text,
	`approved_by` int,
	`approved_at` timestamp,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `purchase_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`request_number` varchar(50) NOT NULL,
	`request_date` date NOT NULL,
	`required_date` date,
	`status` enum('draft','pending','approved','rejected','converted','cancelled') DEFAULT 'draft',
	`priority` enum('low','medium','high','urgent') DEFAULT 'medium',
	`requested_by` int NOT NULL,
	`department_id` int,
	`purpose` text,
	`total_amount` decimal(18,2) DEFAULT '0',
	`approved_by` int,
	`approved_at` timestamp,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `role_permissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`role_id` int NOT NULL,
	`permission_id` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `role_permissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`description` text,
	`level` int DEFAULT 1,
	`is_system` boolean DEFAULT false,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `roles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sensors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`equipment_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`type` enum('voltage','current','power','frequency','temperature','humidity','pressure','flow','level','speed','vibration') NOT NULL,
	`unit` varchar(20) NOT NULL,
	`min_value` decimal(15,4),
	`max_value` decimal(15,4),
	`warning_low` decimal(15,4),
	`warning_high` decimal(15,4),
	`critical_low` decimal(15,4),
	`critical_high` decimal(15,4),
	`current_value` decimal(15,4),
	`last_reading_time` timestamp,
	`status` enum('active','inactive','faulty') DEFAULT 'active',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sensors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sequences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`prefix` varchar(20),
	`suffix` varchar(20),
	`current_value` int DEFAULT 0,
	`min_digits` int DEFAULT 6,
	`reset_period` enum('never','yearly','monthly') DEFAULT 'never',
	`last_reset_date` date,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sequences_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int,
	`category` varchar(50) NOT NULL,
	`key` varchar(100) NOT NULL,
	`value` text,
	`value_type` enum('string','number','boolean','json') DEFAULT 'string',
	`description` text,
	`is_system` boolean DEFAULT false,
	`updated_by` int,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('generation','transmission','distribution','substation','solar','wind','hydro','thermal','nuclear','storage') NOT NULL,
	`status` enum('operational','maintenance','offline','construction','decommissioned') DEFAULT 'operational',
	`capacity` decimal(15,2),
	`capacity_unit` varchar(20) DEFAULT 'MW',
	`voltage_level` varchar(50),
	`address` text,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`commission_date` date,
	`manager_id` int,
	`is_active` boolean DEFAULT true,
	`metadata` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stock_balances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`item_id` int NOT NULL,
	`warehouse_id` int NOT NULL,
	`quantity` decimal(15,3) DEFAULT '0',
	`reserved_qty` decimal(15,3) DEFAULT '0',
	`available_qty` decimal(15,3) DEFAULT '0',
	`average_cost` decimal(18,4) DEFAULT '0',
	`total_value` decimal(18,2) DEFAULT '0',
	`last_movement_date` timestamp,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stock_balances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stock_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`item_id` int NOT NULL,
	`warehouse_id` int NOT NULL,
	`movement_type` enum('receipt','issue','transfer_in','transfer_out','adjustment_in','adjustment_out','return','scrap') NOT NULL,
	`movement_date` datetime NOT NULL,
	`document_type` varchar(50),
	`document_id` int,
	`document_number` varchar(50),
	`quantity` decimal(15,3) NOT NULL,
	`unit_cost` decimal(18,4),
	`total_cost` decimal(18,2),
	`balance_before` decimal(15,3),
	`balance_after` decimal(15,3),
	`notes` text,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stock_movements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('manufacturer','distributor','contractor','service_provider'),
	`contact_person` varchar(100),
	`phone` varchar(50),
	`email` varchar(255),
	`address` text,
	`city` varchar(100),
	`country` varchar(100),
	`tax_number` varchar(50),
	`payment_terms` int DEFAULT 30,
	`credit_limit` decimal(18,2),
	`current_balance` decimal(18,2) DEFAULT '0',
	`account_id` int,
	`rating` int,
	`is_active` boolean DEFAULT true,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_roles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`role_id` int NOT NULL,
	`business_id` int,
	`branch_id` int,
	`station_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_roles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `warehouses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`name_en` varchar(255),
	`type` enum('main','spare_parts','consumables','transit','quarantine') DEFAULT 'main',
	`address` text,
	`manager_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `warehouses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `work_order_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`work_order_id` int NOT NULL,
	`task_number` int NOT NULL,
	`description` text NOT NULL,
	`status` enum('pending','in_progress','completed','skipped') DEFAULT 'pending',
	`assigned_to` int,
	`estimated_hours` decimal(8,2),
	`actual_hours` decimal(8,2),
	`completed_at` timestamp,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `work_order_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `work_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`branch_id` int,
	`station_id` int,
	`order_number` varchar(50) NOT NULL,
	`type` enum('preventive','corrective','emergency','inspection','calibration') NOT NULL,
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`status` enum('draft','pending','approved','assigned','in_progress','on_hold','completed','cancelled','closed') DEFAULT 'draft',
	`asset_id` int,
	`equipment_id` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`requested_by` int,
	`requested_date` datetime,
	`scheduled_start` datetime,
	`scheduled_end` datetime,
	`actual_start` datetime,
	`actual_end` datetime,
	`assigned_to` int,
	`team_id` int,
	`estimated_hours` decimal(8,2),
	`actual_hours` decimal(8,2),
	`estimated_cost` decimal(18,2),
	`actual_cost` decimal(18,2),
	`labor_cost` decimal(18,2),
	`parts_cost` decimal(18,2),
	`completion_notes` text,
	`failure_code` varchar(50),
	`root_cause` text,
	`approved_by` int,
	`approved_at` timestamp,
	`closed_by` int,
	`closed_at` timestamp,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `work_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','super_admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` ADD `employee_id` varchar(20);--> statement-breakpoint
ALTER TABLE `users` ADD `name_ar` varchar(255);--> statement-breakpoint
ALTER TABLE `users` ADD `phone` varchar(50);--> statement-breakpoint
ALTER TABLE `users` ADD `avatar` text;--> statement-breakpoint
ALTER TABLE `users` ADD `business_id` int;--> statement-breakpoint
ALTER TABLE `users` ADD `branch_id` int;--> statement-breakpoint
ALTER TABLE `users` ADD `station_id` int;--> statement-breakpoint
ALTER TABLE `users` ADD `department_id` int;--> statement-breakpoint
ALTER TABLE `users` ADD `job_title` varchar(100);--> statement-breakpoint
ALTER TABLE `users` ADD `is_active` boolean DEFAULT true;