CREATE TABLE `ai_models` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(200) NOT NULL,
	`name_en` varchar(200),
	`description` text,
	`model_type` enum('consumption_forecast','fault_detection','load_optimization','anomaly_detection','demand_prediction','maintenance_prediction','customer_churn','fraud_detection','price_optimization','other') NOT NULL,
	`provider` enum('internal','openai','azure','google','aws','custom') DEFAULT 'internal',
	`model_version` varchar(50),
	`endpoint` varchar(500),
	`input_schema` json,
	`output_schema` json,
	`accuracy` decimal(5,2),
	`last_trained_at` timestamp,
	`training_data_count` int,
	`is_active` boolean DEFAULT true,
	`config` json,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_models_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`model_id` int NOT NULL,
	`business_id` int NOT NULL,
	`prediction_type` varchar(50) NOT NULL,
	`target_entity` varchar(50),
	`target_entity_id` int,
	`input_data` json NOT NULL,
	`prediction` json NOT NULL,
	`confidence` decimal(5,2),
	`prediction_date` date NOT NULL,
	`valid_from` timestamp,
	`valid_to` timestamp,
	`actual_value` json,
	`accuracy` decimal(5,2),
	`is_verified` boolean DEFAULT false,
	`verified_at` timestamp,
	`verified_by` int,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_keys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`key_hash` varchar(255) NOT NULL,
	`key_prefix` varchar(20) NOT NULL,
	`permissions` json,
	`allowed_ips` json,
	`allowed_origins` json,
	`rate_limit_per_minute` int DEFAULT 60,
	`rate_limit_per_day` int DEFAULT 10000,
	`expires_at` timestamp,
	`last_used_at` timestamp,
	`usage_count` int DEFAULT 0,
	`is_active` boolean DEFAULT true,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `api_keys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`api_key_id` int,
	`business_id` int NOT NULL,
	`endpoint` varchar(500) NOT NULL,
	`method` varchar(10) NOT NULL,
	`request_headers` json,
	`request_body` json,
	`response_status` int,
	`response_time` int,
	`ip_address` varchar(50),
	`user_agent` varchar(500),
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`subscriber_name` varchar(100) NOT NULL,
	`event_type` varchar(100) NOT NULL,
	`handler_type` enum('webhook','queue','function','email','sms') NOT NULL,
	`handler_config` json NOT NULL,
	`filter_expression` json,
	`is_active` boolean DEFAULT true,
	`priority` int DEFAULT 0,
	`max_retries` int DEFAULT 3,
	`retry_delay_seconds` int DEFAULT 60,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `incoming_webhooks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`integration_id` int NOT NULL,
	`business_id` int NOT NULL,
	`webhook_type` varchar(100) NOT NULL,
	`payload` json NOT NULL,
	`headers` json,
	`signature` varchar(255),
	`is_valid` boolean DEFAULT true,
	`status` enum('received','processing','processed','failed') DEFAULT 'received',
	`processed_at` timestamp,
	`error_message` text,
	`retry_count` int DEFAULT 0,
	`source_ip` varchar(50),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `incoming_webhooks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `integration_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`integration_id` int NOT NULL,
	`config_key` varchar(100) NOT NULL,
	`config_value` text,
	`is_encrypted` boolean DEFAULT false,
	`value_type` enum('string','number','boolean','json') DEFAULT 'string',
	`environment` enum('production','staging','development') DEFAULT 'production',
	`description` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `integration_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `integration_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`integration_id` int NOT NULL,
	`business_id` int NOT NULL,
	`request_id` varchar(100),
	`direction` enum('outgoing','incoming') NOT NULL,
	`method` varchar(10),
	`endpoint` varchar(500),
	`request_headers` json,
	`request_body` json,
	`response_status` int,
	`response_headers` json,
	`response_body` json,
	`duration_ms` int,
	`status` enum('success','failed','timeout','error') NOT NULL,
	`error_message` text,
	`retry_count` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `integration_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `integrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(200) NOT NULL,
	`name_en` varchar(200),
	`description` text,
	`integration_type` enum('payment_gateway','sms','whatsapp','email','iot','erp','crm','scada','gis','weather','maps','other') NOT NULL,
	`category` enum('local','international','internal') DEFAULT 'local',
	`provider` varchar(100),
	`base_url` varchar(500),
	`api_version` varchar(20),
	`auth_type` enum('api_key','oauth2','basic','hmac','jwt','none') DEFAULT 'api_key',
	`is_active` boolean DEFAULT true,
	`is_primary` boolean DEFAULT false,
	`priority` int DEFAULT 1,
	`last_health_check` timestamp,
	`health_status` enum('healthy','degraded','down','unknown') DEFAULT 'unknown',
	`webhook_url` varchar(500),
	`webhook_secret` varchar(255),
	`rate_limit_per_minute` int DEFAULT 60,
	`timeout_seconds` int DEFAULT 30,
	`retry_attempts` int DEFAULT 3,
	`metadata` json,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `integrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performance_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`metric_type` enum('response_time','throughput','error_rate','cpu_usage','memory_usage','disk_usage','network_io','db_connections','active_users','api_calls','queue_size','cache_hit_rate') NOT NULL,
	`source` varchar(100),
	`value` decimal(15,4) NOT NULL,
	`unit` varchar(20),
	`tags` json,
	`recorded_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `performance_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `system_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`event_type` varchar(100) NOT NULL,
	`event_source` varchar(50) NOT NULL,
	`aggregate_type` varchar(50),
	`aggregate_id` int,
	`payload` json NOT NULL,
	`metadata` json,
	`correlation_id` varchar(100),
	`causation_id` varchar(100),
	`status` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`processed_at` timestamp,
	`error_message` text,
	`retry_count` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `system_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `technical_alert_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(50) NOT NULL,
	`name_ar` varchar(200) NOT NULL,
	`name_en` varchar(200),
	`description` text,
	`category` enum('performance','security','availability','integration','database','api','system') NOT NULL,
	`severity` enum('info','warning','error','critical') DEFAULT 'warning',
	`condition` json NOT NULL,
	`threshold` decimal(15,4),
	`comparison_operator` enum('gt','gte','lt','lte','eq','neq'),
	`evaluation_period_minutes` int DEFAULT 5,
	`cooldown_minutes` int DEFAULT 15,
	`notification_channels` json,
	`escalation_rules` json,
	`auto_resolve` boolean DEFAULT true,
	`is_active` boolean DEFAULT true,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `technical_alert_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `technical_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rule_id` int NOT NULL,
	`business_id` int NOT NULL,
	`alert_type` varchar(50) NOT NULL,
	`severity` enum('info','warning','error','critical') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`source` varchar(100),
	`source_id` varchar(100),
	`current_value` decimal(15,4),
	`threshold_value` decimal(15,4),
	`metadata` json,
	`status` enum('active','acknowledged','resolved','suppressed') DEFAULT 'active',
	`acknowledged_by` int,
	`acknowledged_at` timestamp,
	`resolved_by` int,
	`resolved_at` timestamp,
	`resolution_notes` text,
	`notifications_sent` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `technical_alerts_id` PRIMARY KEY(`id`)
);
