CREATE TABLE `attendance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`business_id` int NOT NULL,
	`attendance_date` date NOT NULL,
	`check_in_time` datetime,
	`check_in_location` varchar(255),
	`check_in_latitude` decimal(10,8),
	`check_in_longitude` decimal(11,8),
	`check_in_method` enum('manual','biometric','gps','qr_code') DEFAULT 'manual',
	`check_out_time` datetime,
	`check_out_location` varchar(255),
	`check_out_latitude` decimal(10,8),
	`check_out_longitude` decimal(11,8),
	`check_out_method` enum('manual','biometric','gps','qr_code') DEFAULT 'manual',
	`total_hours` decimal(5,2),
	`overtime_hours` decimal(5,2) DEFAULT '0',
	`late_minutes` int DEFAULT 0,
	`early_leave_minutes` int DEFAULT 0,
	`status` enum('present','absent','late','half_day','leave','holiday','weekend') DEFAULT 'present',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attendance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `departments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`parent_id` int,
	`manager_id` int,
	`cost_center_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `departments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employee_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`business_id` int NOT NULL,
	`contract_number` varchar(50) NOT NULL,
	`contract_type` enum('permanent','fixed_term','temporary','probation') DEFAULT 'permanent',
	`start_date` date NOT NULL,
	`end_date` date,
	`basic_salary` decimal(15,2),
	`probation_period_days` int DEFAULT 90,
	`notice_period_days` int DEFAULT 30,
	`document_path` varchar(500),
	`status` enum('active','expired','terminated','renewed') DEFAULT 'active',
	`termination_date` date,
	`termination_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_contracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`employee_number` varchar(20) NOT NULL,
	`first_name` varchar(100) NOT NULL,
	`middle_name` varchar(100),
	`last_name` varchar(100) NOT NULL,
	`full_name_ar` varchar(200),
	`full_name_en` varchar(200),
	`id_type` enum('national_id','passport','residence') DEFAULT 'national_id',
	`id_number` varchar(50) NOT NULL,
	`id_expiry_date` date,
	`nationality` varchar(50),
	`gender` enum('male','female') DEFAULT 'male',
	`date_of_birth` date,
	`place_of_birth` varchar(100),
	`marital_status` enum('single','married','divorced','widowed') DEFAULT 'single',
	`phone` varchar(20),
	`mobile` varchar(20) NOT NULL,
	`email` varchar(100),
	`personal_email` varchar(100),
	`address` text,
	`city` varchar(100),
	`district` varchar(100),
	`emergency_contact_name` varchar(100),
	`emergency_contact_phone` varchar(20),
	`emergency_contact_relation` varchar(50),
	`photo_path` varchar(500),
	`hire_date` date NOT NULL,
	`probation_end_date` date,
	`contract_type` enum('permanent','contract','temporary','part_time') DEFAULT 'permanent',
	`contract_start_date` date,
	`contract_end_date` date,
	`job_title_id` int,
	`department_id` int,
	`manager_id` int,
	`is_manager` boolean DEFAULT false,
	`work_location` varchar(100),
	`station_id` int,
	`branch_id` int,
	`work_schedule` enum('full_time','shift','flexible') DEFAULT 'full_time',
	`working_hours_per_week` decimal(5,2) DEFAULT '40',
	`field_worker_id` int,
	`status` enum('active','inactive','terminated','suspended','on_leave') DEFAULT 'active',
	`termination_date` date,
	`termination_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employees_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `job_titles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`title_ar` varchar(100) NOT NULL,
	`title_en` varchar(100),
	`department_id` int,
	`grade_id` int,
	`level` int DEFAULT 1,
	`description` text,
	`responsibilities` text,
	`requirements` text,
	`headcount` int DEFAULT 1,
	`current_count` int DEFAULT 0,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `job_titles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leave_balances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`leave_type_id` int NOT NULL,
	`year` int NOT NULL,
	`opening_balance` int DEFAULT 0,
	`earned_balance` int DEFAULT 0,
	`used_balance` int DEFAULT 0,
	`adjustment_balance` int DEFAULT 0,
	`remaining_balance` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leave_balances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leave_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`business_id` int NOT NULL,
	`leave_type_id` int NOT NULL,
	`start_date` date NOT NULL,
	`end_date` date NOT NULL,
	`total_days` int NOT NULL,
	`reason` text,
	`attachment_path` varchar(500),
	`status` enum('pending','approved','rejected','cancelled') DEFAULT 'pending',
	`approved_by` int,
	`approved_at` timestamp NULL DEFAULT NULL,
	`rejection_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leave_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leave_types` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name_ar` varchar(100) NOT NULL,
	`name_en` varchar(100),
	`annual_balance` int DEFAULT 0,
	`is_paid` boolean DEFAULT true,
	`requires_approval` boolean DEFAULT true,
	`allows_carry_over` boolean DEFAULT false,
	`max_carry_over_days` int DEFAULT 0,
	`color` varchar(20) DEFAULT '#3B82F6',
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `leave_types_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payroll_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payroll_run_id` int NOT NULL,
	`employee_id` int NOT NULL,
	`basic_salary` decimal(15,2) NOT NULL,
	`working_days` int DEFAULT 30,
	`actual_days` int DEFAULT 30,
	`housing_allowance` decimal(15,2) DEFAULT '0',
	`transport_allowance` decimal(15,2) DEFAULT '0',
	`other_allowances` decimal(15,2) DEFAULT '0',
	`total_allowances` decimal(15,2) DEFAULT '0',
	`overtime_hours` decimal(10,2) DEFAULT '0',
	`overtime_amount` decimal(15,2) DEFAULT '0',
	`bonuses` decimal(15,2) DEFAULT '0',
	`total_additions` decimal(15,2) DEFAULT '0',
	`absence_days` int DEFAULT 0,
	`absence_deduction` decimal(15,2) DEFAULT '0',
	`late_deduction` decimal(15,2) DEFAULT '0',
	`social_insurance` decimal(15,2) DEFAULT '0',
	`tax_deduction` decimal(15,2) DEFAULT '0',
	`loan_deduction` decimal(15,2) DEFAULT '0',
	`other_deductions` decimal(15,2) DEFAULT '0',
	`total_deductions` decimal(15,2) DEFAULT '0',
	`gross_salary` decimal(15,2),
	`net_salary` decimal(15,2),
	`status` enum('calculated','approved','paid') DEFAULT 'calculated',
	`paid_at` timestamp NULL DEFAULT NULL,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payroll_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payroll_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`period_year` int NOT NULL,
	`period_month` int NOT NULL,
	`period_start_date` date NOT NULL,
	`period_end_date` date NOT NULL,
	`total_basic_salary` decimal(15,2) DEFAULT '0',
	`total_allowances` decimal(15,2) DEFAULT '0',
	`total_deductions` decimal(15,2) DEFAULT '0',
	`total_net_salary` decimal(15,2) DEFAULT '0',
	`employee_count` int DEFAULT 0,
	`status` enum('draft','calculated','approved','paid','cancelled') DEFAULT 'draft',
	`journal_entry_id` int,
	`calculated_at` timestamp NULL DEFAULT NULL,
	`calculated_by` int,
	`approved_at` timestamp NULL DEFAULT NULL,
	`approved_by` int,
	`paid_at` timestamp NULL DEFAULT NULL,
	`paid_by` int,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performance_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`business_id` int NOT NULL,
	`evaluation_period` varchar(50) NOT NULL,
	`period_start_date` date NOT NULL,
	`period_end_date` date NOT NULL,
	`overall_score` decimal(5,2),
	`performance_rating` enum('exceptional','exceeds','meets','needs_improvement','unsatisfactory'),
	`quality_score` decimal(5,2),
	`productivity_score` decimal(5,2),
	`attendance_score` decimal(5,2),
	`teamwork_score` decimal(5,2),
	`initiative_score` decimal(5,2),
	`strengths` text,
	`areas_for_improvement` text,
	`goals` text,
	`manager_comments` text,
	`employee_comments` text,
	`evaluated_by` int NOT NULL,
	`evaluated_at` timestamp NULL DEFAULT NULL,
	`status` enum('draft','submitted','reviewed','acknowledged') DEFAULT 'draft',
	`acknowledged_at` timestamp NULL DEFAULT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `performance_evaluations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salary_details` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`basic_salary` decimal(15,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'SAR',
	`housing_allowance` decimal(15,2) DEFAULT '0',
	`transport_allowance` decimal(15,2) DEFAULT '0',
	`food_allowance` decimal(15,2) DEFAULT '0',
	`phone_allowance` decimal(15,2) DEFAULT '0',
	`other_allowances` decimal(15,2) DEFAULT '0',
	`total_salary` decimal(15,2),
	`payment_method` enum('bank_transfer','cash','check') DEFAULT 'bank_transfer',
	`bank_name` varchar(100),
	`bank_account_number` varchar(50),
	`iban` varchar(50),
	`effective_date` date NOT NULL,
	`end_date` date,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `salary_details_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salary_grades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`name` varchar(100) NOT NULL,
	`min_salary` decimal(15,2),
	`max_salary` decimal(15,2),
	`housing_allowance_pct` decimal(5,2) DEFAULT '0',
	`transport_allowance` decimal(15,2) DEFAULT '0',
	`is_active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `salary_grades_id` PRIMARY KEY(`id`)
);
